<?php

namespace App\HttpController\Api;

use EasySwoole\Core\Http\AbstractInterface\Controller;
use App\HttpController\Api\Base;
use \EasySwoole\Core\Component\Di;
use App\Lib\Redis\Redis;

/**
 * Class Index
 * @package App\HttpController
 */
class Index extends Controller
{
    public function onRequest($action): ?bool
    {
        return true;
        return $this->writeJson('403','您么有访问权限','');
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }

    /**
     * 首页方法
     * @author : evalor <master@evalor.cn>
     */
    function index()
    {
        $data   = [
            'id'  => '1',
            'name' => 'summer_li2018000年11月8日20:46:13'
        ];
        return $this->writeJson(200,'ok',$data);
    }
    public function video()
    {
        $params = $this->request()->getRequestParam();
        $data = [
          'params' => $params
        ];
        return $this->writeJson(200,'nice',$data);
    }
    public function getVideo(){
        $db = Di::getInstance()->get("MYSQL");
        $result = $db->where("id",1)->getOne("video");
        return $this->writeJson('200','ok',$result);
    }
    public function getRedis(){

//        $result = Redis::getInstance()->get('summer1');
        $result = Di::getInstance()->get("REDIS")->get('summer');
        return $this->writeJson(200,"ok",$result);
    }
}